groups:
  - name: notable_application
    interval: 30s
    rules:
      # High error rate alert
      - alert: HighErrorRate
        expr: rate(notable_errors_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
          service: notable
        annotations:
          summary: 'High error rate detected'
          description: 'Error rate is {{ $value }} errors/sec (threshold: 0.05)'

      # Critical error rate alert
      - alert: CriticalErrorRate
        expr: rate(notable_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
          service: notable
        annotations:
          summary: 'Critical error rate detected'
          description: 'Error rate is {{ $value }} errors/sec (threshold: 0.1)'

      # Application down alert
      - alert: ApplicationDown
        expr: up{job="notable-app"} == 0
        for: 1m
        labels:
          severity: critical
          service: notable
        annotations:
          summary: 'Notable application is down'
          description: 'The Notable application has been down for more than 1 minute'

      # High response time alert
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(notable_http_request_duration_ms[5m])) > 1000
        for: 5m
        labels:
          severity: warning
          service: notable
        annotations:
          summary: 'High response time detected'
          description: '95th percentile response time is {{ $value }}ms (threshold: 1000ms)'

      # Low authentication success rate
      - alert: LowAuthSuccessRate
        expr: rate(notable_auth_successes_total[5m]) / rate(notable_auth_attempts_total[5m]) < 0.8
        for: 10m
        labels:
          severity: warning
          service: notable
        annotations:
          summary: 'Low authentication success rate'
          description: 'Auth success rate is {{ $value }} (threshold: 80%)'

      # High memory usage alert
      - alert: HighMemoryUsage
        expr: notable_nodejs_memory_usage_bytes{type="heapUsed"} / notable_nodejs_memory_usage_bytes{type="heapTotal"} > 0.9
        for: 5m
        labels:
          severity: warning
          service: notable
        annotations:
          summary: 'High memory usage detected'
          description: 'Heap usage is {{ $value }}% (threshold: 90%)'

      # Database connection failures
      - alert: DatabaseConnectionFailure
        expr: increase(notable_database_connection_errors_total[5m]) > 5
        for: 2m
        labels:
          severity: critical
          service: notable
        annotations:
          summary: 'Database connection failures detected'
          description: '{{ $value }} database connection failures in the last 5 minutes'

      # Search service degradation
      - alert: SearchServiceDegraded
        expr: histogram_quantile(0.95, rate(notable_search_duration_ms[5m])) > 500
        for: 10m
        labels:
          severity: warning
          service: notable
        annotations:
          summary: 'Search service performance degraded'
          description: '95th percentile search time is {{ $value }}ms (threshold: 500ms)'

      # Note creation failures
      - alert: NoteCreationFailures
        expr: rate(notable_note_creation_failures_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
          service: notable
        annotations:
          summary: 'Note creation failures detected'
          description: 'Note creation failure rate is {{ $value }} (threshold: 0.01)'

      # Realtime sync issues
      - alert: RealtimeSyncIssues
        expr: notable_realtime_disconnections_total > 10
        for: 5m
        labels:
          severity: warning
          service: notable
        annotations:
          summary: 'Realtime sync experiencing disconnections'
          description: '{{ $value }} realtime disconnections detected'
