# Codecov configuration for Notable E2E coverage

coverage:
  # Progressive coverage targets for E2E tests
  # Current: 64% → Target: 70% → Future: 80-90%
  status:
    project:
      default:
        target: 70% # Realistic target based on current 64% achievement
        threshold: 5% # Allow 5% variance to prevent flaky failures
        base: auto
        flags:
          - e2e
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 60% # New code should have reasonable E2E coverage
        threshold: 5%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false

  # Coverage precision
  precision: 2
  round: down
  range: '90...100'

# Parser configuration
parsers:
  javascript:
    enable_partials: yes

# Comment settings
comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  branches:
    - 'main'
    - 'master'

# Flag configuration for E2E tests
flags:
  e2e:
    paths:
      - packages/web/
    carryforward: false

# Ignore patterns
ignore:
  - '**/*.test.ts'
  - '**/*.spec.ts'
  - '**/test/**'
  - '**/tests/**'
  - '**/e2e/**'
  - '**/__tests__/**'
  - '**/__mocks__/**'
  - '**/node_modules/**'
  - '**/.next/**'
  - '**/coverage/**'
  - '**/dist/**'
  - '**/build/**'
  - '**/*.config.js'
  - '**/*.config.ts'
  - '**/scripts/**'

# Codecov settings
codecov:
  notify:
    # Notify when coverage drops below 100%
    after_n_builds: 1
    wait_for_ci: true

  # Require CI to pass
  require_ci_to_pass: true

  # Bot configuration
  bot: 'codecov-io'

  # Branch configuration
  branch: main

  # Strict mode - fail if coverage is below target
  strict_yaml_branch: main
