codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: '90...100'

  status:
    project:
      default:
        target: 100%
        threshold: 0%
        base: auto
        flags:
          - e2e
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: 'reach,diff,flags,files,footer'
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

flags:
  e2e:
    paths:
      - packages/web/
    carryforward: false
