packages:
  - packages/*
  - packages/configs/*

onlyBuiltDependencies:
  - '@sentry/cli'
  - '@tailwindcss/oxide'
  - core-js
  - detox
  - dtrace-provider
  - electron
  - electron-winstaller
  - esbuild
  - msgpackr-extract
  - oxc-resolver
  - sharp
  - supabase
  - unrs-resolver
