services:
  # Test PostgreSQL Database
  test-db:
    image: postgres:17-alpine
    ports:
      - "5433:5432" # Different port to avoid conflicts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: notable_test
    volumes:
      - ./e2e/fixtures/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
      - ./e2e/fixtures/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql:ro
    networks:
      - test-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Test Redis (for caching/sessions if needed)
  test-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379" # Different port to avoid conflicts
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  test-network:
    driver: bridge
