export default {
  all: true,
  include: [
    'src/**/*.{js,jsx,ts,tsx}',
    'app/**/*.{js,jsx,ts,tsx}',
    'lib/**/*.{js,jsx,ts,tsx}',
    'components/**/*.{js,jsx,ts,tsx}',
    'features/**/*.{js,jsx,ts,tsx}',
  ],
  exclude: [
    '**/*.test.{js,jsx,ts,tsx}',
    '**/*.spec.{js,jsx,ts,tsx}',
    '**/*.stories.{js,jsx,ts,tsx}',
    '**/node_modules/**',
    'coverage/**',
    '.next/**',
    '.next_coverage/**',
    'public/**',
    'e2e/**',
    '**/*.d.ts',
    'next.config.mjs',
    'babel.config.js',
    'nyc.config.js',
  ],
  reporter: ['text', 'json', 'lcov', 'html'],
  'report-dir': './coverage',
  'temp-dir': './.nyc_output',
  'check-coverage': true,
  branches: 100,
  lines: 100,
  functions: 100,
  statements: 100,
}
