name: E2E Tests with Coverage

on:
  push:
    branches: [main]
  pull_request:

jobs:
  e2e-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: |
          cd packages/web
          npx playwright install --with-deps chromium

      - name: Build the application
        run: |
          cd packages/web
          pnpm build

      - name: Run E2E tests with coverage
        env:
          CI: 'true'
          NODE_ENV: 'test'
          NEXT_PUBLIC_SUPABASE_URL: 'https://placeholder.supabase.co'
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'placeholder-anon-key'
          NEXT_PUBLIC_APP_URL: 'http://localhost:4378'
        run: |
          cd packages/web
          pnpm e2e:coverage:ci

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: packages/web/coverage/lcov.info
          flags: e2e
          name: e2e-coverage
          fail_ci_if_error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/web/playwright-report/
          retention-days: 30

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: packages/web/coverage/
          retention-days: 30
