name: E2E Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

env:
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: System Information
        run: |
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h
          echo "Disk Info:"
          df -h

      - name: Optimize CI Environment
        run: |
          # Free up disk space
          sudo apt clean
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true

          # Set resource limits for Node.js
          echo "NODE_OPTIONS=--max-old-space-size=4096" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: |
          # Install only chromium to match optimized test configuration
          timeout 300 npx playwright install --with-deps chromium || {
            echo "Chromium installation failed or timed out"
            exit 1
          }
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 0
          PLAYWRIGHT_BROWSERS_PATH: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - name: Verify Browser Installation
        run: |
          echo "Verifying browser installations..."
          npx playwright --version
          ls -la ${{ env.PLAYWRIGHT_BROWSERS_PATH }} || echo "Browser directory not found"

      - name: Build workspace dependencies
        run: pnpm build --filter=@notable/sync --filter=@notable/routing

      - name: Clear Next.js cache
        run: |
          cd packages/web
          rm -rf .next .turbo

      - name: Build Next.js app
        run: |
          cd packages/web
          pnpm build
        env:
          NEXT_PUBLIC_SUPABASE_URL: 'https://placeholder.supabase.co'
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'placeholder-anon-key'
          NEXT_PUBLIC_APP_URL: 'http://localhost:4378'
          NEXT_PUBLIC_API_MOCKING: 'enabled'

      - name: Verify build output
        run: |
          cd packages/web
          echo "Checking build output..."
          ls -la .next/
          echo "Checking if standalone output exists..."
          ls -la .next/standalone/ || echo "No standalone build found"

      - name: Run E2E Tests
        run: |
          cd packages/web
          echo "Starting E2E tests..."
          echo "Current working directory: $(pwd)"
          echo "Build output exists: $(ls -la .next/ | head -5)"
          pnpm run e2e --reporter=list
        env:
          CI: true
          PLAYWRIGHT_BROWSERS_PATH: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          # Minimal env vars for Next.js to start
          NEXT_PUBLIC_SUPABASE_URL: 'https://placeholder.supabase.co'
          NEXT_PUBLIC_SUPABASE_ANON_KEY: 'placeholder-anon-key'
          NEXT_PUBLIC_APP_URL: 'http://localhost:4378'
          NEXT_PUBLIC_API_MOCKING: 'enabled'
          NODE_ENV: 'production'
          DEBUG: 'pw:webserver'

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: packages/web/playwright-report/
          retention-days: 30

      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-videos
          path: packages/web/test-results/
          retention-days: 7
